version: "3.1"
services:

    mysql:
      image: mysql:8.0.16
      container_name: ci-starter-mysql
      working_dir: /public_html
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - ./phpdocker/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=phpapp
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: ci-starter-webserver
      working_dir: /public_html
      volumes:
          - .:/public_html
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/nginx/log:/var/log/nginx/
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ci-starter-php-fpm
      working_dir: /public_html
      volumes:
        - .:/public_html
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    
    adminer:
      image: adminer
      container_name: ci-starter-adminer
      restart: always
      ports:
        - 8080:8080
